### ISSUE TITLE
Got "Index was outside the bounds of the array" after doing a search.

### ISSUE THREAD

**Issue by Nutzzz** [Nutzzz/GLC#36]
This is really just a reminder for myself, I'll take a look when I get a chance.

I had a platform selected, but the behavior does not appear to be consistent.

```
Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at GameLauncher_Console.CConsoleHelper.HandleNavigationMenu(Int32 nStartY, Int32 nStopY, ConfigVolatile cfgv, Hotkeys keys, Colours cols, Boolean setup, Boolean browse, String& game, String[] options) in C:\Users\enuss\source\repos\GLC\GameLauncher_Console\GameLauncher_Console\ConsoleHelper.cs:line 0
   at GameLauncher_Console.CConsoleHelper.DisplayMenu(ConfigVolatile cfgv, Hotkeys keys, Colours cols, String& game, String[] options) in C:\Users\enuss\source\repos\GLC\GameLauncher_Console\GameLauncher_Console\ConsoleHelper.cs:line 511
   at GameLauncher_Console.CDock.MenuSwitchboard(ConfigVolatile cfgv, Hotkeys keys, Colours cols, Boolean& setup, Boolean& browse, String& path, String& gameSearch, Int32& nSelectionCode) in C:\Users\enuss\source\repos\GLC\GameLauncher_Console\GameLauncher_Console\Dock.cs:line 1021
   at GameLauncher_Console.CDock.MainLoop(String[] args) in C:\Users\enuss\source\repos\GLC\GameLauncher_Console\GameLauncher_Console\Dock.cs:line 283
   at GameLauncher_Console.Program.Main(String[] args) in C:\Users\enuss\source\repos\GLC\GameLauncher_Console\GameLauncher_Console\Program.cs:line 34
```

**Comment by Nutzzz** [comment]
Fixed by PR #45
